"""Stage market lists into app/data/{SYM}.json (same schema as fetch_stooq.py).

Symbols are extracted from every symbols:[...] array in app/markets.js (regex),
plus the var DOW30 = [...] declaration (that entry references the var).
app/markets.js is generated by scripts/fetch_constituents.py from Wikipedia
(DOW30=30, NDQ100=102, SP500=503, 10 derived GICS sector lists, local-only
ARKK/CRYPTO/ETF100/R2000) — so rerunning this script is how the new members
get their price history. Run once to stage all lists:
    /usr/bin/python3 scripts/fetch_market.py
Requires: pip3 install yfinance (present on /usr/bin/python3)
"""
import json
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from fetch_stooq import OUT, fetch_one, _merge  # reuse schema + merge

MARKETS_JS = ROOT / "app" / "markets.js"

def all_symbols():
    """Extract every symbols:[...] list from markets.js (JSON-ish via regex),
    plus the var DOW30 = [...] declaration (that entry references the var)."""
    txt = MARKETS_JS.read_text()
    syms = set()
    for m in re.finditer(r'symbols:\s*\[([^\]]*)\]', txt):
        for s in re.findall(r'"([A-Z0-9.\-]{1,10})"', m.group(1)):
            syms.add(s)
    for m in re.finditer(r'var\s+DOW30\s*=\s*\[([^\]]*)\]', txt):
        for s in re.findall(r'"([A-Z0-9.\-]{1,10})"', m.group(1)):
            syms.add(s)
    return sorted(syms)

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    want = set(all_symbols())
    have = {p.stem for p in OUT.glob("*.json")}
    todo = sorted(want - have)
    print(f"markets.js lists {len(want)} unique symbols; {len(have)} already saved; {len(todo)} to fetch", flush=True)
    failed = []
    for n, sym in enumerate(todo, 1):
        try:
            candles, vols, fresh5m, fresh1h = fetch_one(sym)
        except Exception as e:
            print(f"[{n}/{len(todo)}] {sym} MISS {e}", flush=True)
            failed.append(sym)
            continue
        fp = OUT / f"{sym}.json"
        prev = {}
        if fp.exists():
            prev = json.loads(fp.read_text())
        payload = {"symbol": sym, "source": "yfinance",
                   "fetched": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                   "candles": candles, "vols": vols,
                   "bars5m": _merge(prev.get("bars5m"), fresh5m),
                   "bars1h": _merge(prev.get("bars1h"), fresh1h)}
        fp.write_text(json.dumps(payload))
        print(f"[{n}/{len(todo)}] {sym} daily={len(candles)} 5m={len(fresh5m)} 1h={len(fresh1h)} close={candles[-1]['close']}", flush=True)
        time.sleep(1)
    print(f"\nDONE fetched={len(todo)-len(failed)} failed={failed or 'none'}", flush=True)
    return 1 if failed else 0

if __name__ == "__main__":
    sys.exit(main())