"""Stage market lists into app/data/{SYM}.json (same schema as fetch_stooq.py).

Price symbols are extracted from every priceSymbols:[...] array in app/markets.js.
The larger membership-only lists are intentionally not sent to Yahoo.
app/markets.js is generated by scripts/fetch_constituents.py from the watchlist
JSON source with Wikipedia fallback (DOW30=30, NDQ100=102, SP500=503, 10 derived GICS sector lists, local-only
ARKK/CRYPTO/ETF100/R2000) — so rerunning this script is how the new members
get their price history. Run once to stage all lists:
    /usr/bin/python3 scripts/fetch_market.py
Refresh existing daily files in a controlled pilot:
    /usr/bin/python3 scripts/fetch_market.py --refresh-existing --daily-only --limit 5
Requires: pip3 install yfinance (present on /usr/bin/python3)
"""
import argparse
import json
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

MARKETS_JS = ROOT / "app" / "markets.js"

def all_symbols(path=None):
    """Extract only priceSymbols lists from markets.js.

    Membership-only symbols (full `symbols` arrays) are intentionally
    ignored so Yahoo is only asked for the bounded price universe.
    `path` is injectable for unit tests; defaults to app/markets.js.
    """
    txt = Path(path or MARKETS_JS).read_text()
    syms = set()
    for m in re.finditer(r'priceSymbols:\s*\[([^\]]*)\]', txt):
        for s in re.findall(r'"([A-Z0-9.\-]{1,10})"', m.group(1)):
            syms.add(s)
    return sorted(syms)

def main(argv=None):
    ap = argparse.ArgumentParser(description="Fetch market history into app/data")
    ap.add_argument("--refresh-existing", action="store_true",
                    help="refresh symbols whose JSON files already exist")
    ap.add_argument("--daily-only", action="store_true",
                    help="skip 5m and 1h Yahoo requests; preserve archived intraday bars")
    ap.add_argument("--limit", type=int,
                    help="process at most N symbols, in sorted symbol order")
    ap.add_argument("--start-after",
                    help="resume after this symbol in sorted order")
    args = ap.parse_args(argv)

    # Heavy deps (pandas/yfinance) are only needed for actual fetching.
    # Import lazily so --help and static universe checks work on a bare
    # interpreter that only has the stdlib.
    sys.path.insert(0, str(ROOT / "scripts"))
    try:
        from fetch_stooq import OUT, fetch_one, _merge  # reuse schema + merge
    except ModuleNotFoundError as e:
        ap.error("fetching needs yfinance+pandas "
                 "(run the pinned interpreter, e.g. /usr/bin/python3): %s" % e)

    OUT.mkdir(parents=True, exist_ok=True)
    want = set(all_symbols())
    have = {p.stem for p in OUT.glob("*.json")}
    todo = sorted(want if args.refresh_existing else want - have)
    if args.start_after:
        todo = [sym for sym in todo if sym > args.start_after.upper()]
    if args.limit is not None:
        if args.limit < 1:
            ap.error("--limit must be at least 1")
        todo = todo[:args.limit]
    print(f"markets.js lists {len(want)} unique symbols; {len(have)} already saved; {len(todo)} to fetch", flush=True)
    failed = []
    for n, sym in enumerate(todo, 1):
        try:
            candles, vols, fresh5m, fresh1h = fetch_one(
                sym, include_intraday=not args.daily_only)
        except Exception as e:
            print(f"[{n}/{len(todo)}] {sym} MISS {e}", flush=True)
            failed.append(sym)
            continue
        fp = OUT / f"{sym}.json"
        prev = {}
        if fp.exists():
            prev = json.loads(fp.read_text())
        payload = {"symbol": sym, "source": "yfinance",
                   "fetched": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                   "candles": candles, "vols": vols,
                   "bars5m": _merge(prev.get("bars5m"), fresh5m),
                   "bars1h": _merge(prev.get("bars1h"), fresh1h)}
        fp.write_text(json.dumps(payload))
        print(f"[{n}/{len(todo)}] {sym} daily={len(candles)} 5m={len(fresh5m)} 1h={len(fresh1h)} close={candles[-1]['close']}", flush=True)
        time.sleep(1)
    print(f"\nDONE fetched={len(todo)-len(failed)} failed={failed or 'none'}", flush=True)
    return 1 if failed else 0

if __name__ == "__main__":
    sys.exit(main())